annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/display-name: Evroc
  catalog.cattle.io/rancher-version: '>= 2.10.0'
  catalog.cattle.io/ui-extensions-version: '>= 3.0.0 < 4.0.0'
apiVersion: v2
appVersion: 0.1.6
description: Custom UI components for the Evroc Rancher node driver
name: rancher-ui-extension-evroc
type: application
version: 0.1.6
icon: icon.svg
